create table JDENTAL.USER_T (
USER_ID INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY, 
USER_LOGIN VARCHAR(255) not null unique,
USER_EMAIL VARCHAR(255) not null unique,
USER_PASSWD VARCHAR(255) not null unique,
USER_APPVD INT,
USER_TYPE INT,
USER_REG_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT TIMESTAMP);

INSERT INTO JDENTAL.USER_T (USER_LOGIN,USER_EMAIL,USER_PASSWD,USER_APPVD,USER_TYPE)VALUES('root','root@localhost','toor',1,1)